//기초 레이아웃 담당 이름변경은 하지 않기
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import Link from 'next/link'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Blog App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="ko"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <header>
          <nav>
            <Link href="/" className="p-2">
              메인
            </Link>
            <Link href="/posts" className="p-2">
              포스트
            </Link>
            <Link href="/signup" className="p-2">
              회원가입
            </Link>
          </nav>
        </header>
        {children}
        <footer className="p-2">풋터</footer>
      </body>
    </html>
  )
}
